name: Build IPA
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - name: Build
        run: flutter build ipa
      - run: ls
      - run: ls build
      - run: ls -R .
      - name: Package
        run: tar -cvf koel_player.tar build/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: KoelPlayer.tar
          path: koel_player.tar
